name: exercice-laravel-masanet-mr-robot
recipe: laravel
config:
  webroot: ./public/
services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
     - database
  node:
    type: node:14
    build:
      - npm install
tooling:
  npm:
    service: node
  npx:
    service: node
  node:
    service: node
